apiVersion: v1
kind: Service
metadata:
  name: cncf-fallback
  namespace: demo-apps
  labels:
    app: cncf-fallback
    backstage.io/kubernetes-id: cncf-fallback
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: cncf-fallback
